const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('apiTurso', {
  registrarUsuario: (dados) => ipcRenderer.invoke('registrar-usuario', dados),
  loginUsuario: (dados) => ipcRenderer.invoke('login-usuario', dados),
  loginGoogle: (dados) => ipcRenderer.invoke('login-google', dados),
  carregarContas: (dados) => ipcRenderer.invoke('carregar-contas', dados),
  criarConta: (dados) => ipcRenderer.invoke('criar-conta', dados),
  deletarConta: (dados) => ipcRenderer.invoke('deletar-conta', dados),
  carregarCategorias: (dados) => ipcRenderer.invoke('carregar-categorias', dados),
  adicionarCategoria: (dados) => ipcRenderer.invoke('adicionar-categoria', dados),
  deletarCategoria: (dados) => ipcRenderer.invoke('deletar-categoria', dados),
  carregarEtiquetas: (dados) => ipcRenderer.invoke('carregar-etiquetas', dados),
  adicionarEtiqueta: (dados) => ipcRenderer.invoke('adicionar-etiqueta', dados),
  carregarTransacoes: (dados) => ipcRenderer.invoke('carregar-transacoes', dados),
  adicionarTransacao: (dados) => ipcRenderer.invoke('adicionar-transacao', dados),
  editarTransacao: (dados) => ipcRenderer.invoke('editar-transacao', dados),
  deletarTransacao: (dados) => ipcRenderer.invoke('deletar-transacao', dados),
  exportarCSV: (dados) => ipcRenderer.invoke('exportar-csv', dados),
  exportarPDF: (dados) => ipcRenderer.invoke('exportar-pdf', dados),
  obterTotalCaixinha: (dados) => ipcRenderer.invoke('obter-total-caixinha', dados),
  obterHistoricoCaixinha: (dados) => ipcRenderer.invoke('obter-historico-caixinha', dados),
  enviarCodigoVerificacao: (dados) => ipcRenderer.invoke('enviar-codigo-verificacao', dados),
  validarCodigoVerificacao: (dados) => ipcRenderer.invoke('validar-codigo-verificacao', dados),
  solicitarRecuperacaoSenha: (dados) => ipcRenderer.invoke('solicitar-recuperacao-senha', dados),
  confirmarRecuperacaoSenha: (dados) => ipcRenderer.invoke('confirmar-recuperacao-senha', dados),
  obterPerfilUsuario: (dados) => ipcRenderer.invoke('obter-perfil-usuario', dados),
  listarUsuariosAdmin: (dados) => ipcRenderer.invoke('listar-usuarios-admin', dados),
  deletarUsuarioAdmin: (dados) => ipcRenderer.invoke('deletar-usuario-admin', dados),
  alterarFuncaoUsuarioAdmin: (dados) => ipcRenderer.invoke('alterar-funcao-usuario-admin', dados),
});
